# Generated by Django 4.2 on 2023-10-12 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecoveryCode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=200)),
                ('verificationCode', models.IntegerField()),
                ('expiration', models.DateTimeField(db_index=True)),
                ('attempt', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegisterCode',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=200)),
                ('code', models.IntegerField()),
                ('expiration', models.DateTimeField(db_index=True)),
                ('attempt', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryAccountSpecialId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.IntegerField(default=0)),
                ('accountToRecover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_recover', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
